# add your sample (e.g., "strain_01") & reference (e.g., "ref_genome") names below

samples:
  - sample_1
  - sample_2
  - ...

conditions:
  test: [sample_1, sample_2, ...]
  control: [sample_3, sample_4, ...]

read_length: 150
strandedness: 0

read_extension: "fastq.gz"
outdir: "FASTQ/trimmed"
ref_assembly: "reference/ref_assembly.fasta"
ref_annotations: "reference/ref_annotations.gtf"
